### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by levudeptraai** [epicstudios856/Vectras-windows-emulator#15]
Can not create vm
**Time Of Crash :    2024_03_11-12_02_58
Device :    vsmart, Live
Android Version :    10 (29)
App Version :    v2.7 (12)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    vsmart/V620A_open/V620A:10/QKQ1.191215.002/V620A_OPN_U_B14_210717:user/release-keys

java.lang.RuntimeException: java.util.zip.ZipException: invalid stored block lengths
	at com.vectras.vm.RomsManagerActivity$6.run(RomsManagerActivity.java:504)
Caused by: java.util.zip.ZipException: invalid stored block lengths
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:183)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:208)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.vectras.vm.RomsManagerActivity$6.run(RomsManagerActivity.java:493)**
Error 2:
![Screenshot_20240311-122209](https://github.com/epicstudios856/Vectras-windows-emulator/assets/121751949/2c2b2591-7114-4d4e-8495-23f83bab5ec3)

**Comment by epicstudios856** [comment]
The error in screenshot is not error

But the exception says its error when importing rom

What rom u are trying to import?

**Comment by epicstudios856** [comment]
@levudeptraai Rom name

**Comment by epicstudios856** [comment]
@levudeptraai Error2:
Is not error bcuz its debug version just ignore it
